### ISSUE TITLE
Feature - Multi select Drag drop

### ISSUE THREAD

**Issue by gamefundas** [mrf28/a2gtm#5]
Thanks for creating this project, serves as a good foundation for Kanban. I am working to use this as a framework for building an UI and one of my use case requires that I be able to select multiple cards at a time for a bulk move.

I can change the card template to add some sort of check boxes that allows me to select items but wonder if I will be able to drag multiple elements like the functionality Wekan offers. Wanted to check with you @mrf28 to see if this would be possible and if you could point me the right direction how to achieve it.

Can then contribute back when I get it implemented to this project.

**Comment by mrf28** [comment]
Hello @gamefundas,

This project is heavily inspired in trello. I plan to add more features in the future, but following the concepts of simplicity. The feature I would implement for a bulk move is something like "move all the cards in this list".

Feel free to add the feature into your project. If I could suggest a UX for it, I'd recommend you to implement a selection mode, activated by a toggle in some men. Then on selection mode active, highlight the border of the selected cards on click. And finally drag the cards to the desired column, or choose the list on a dialog box.

I'm planing to add a road-map with the features to be added in this project for people who want to contribute.

Best,
Marcos
